Models/Pergunta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap01.Models
{
    public class Pergunta
    {
        public int Id { get; set; }
        [Required]
        public string Descricao { get; set; }
        public string Autor { get; set; }
    }
}

Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Fiap01.Controllers
{
    public class AutorController : Controller
    {
        public IActionResult Index(string nome)
        {
            return View();
        }

        public IActionResult ListaDosAutoresDoAno(int ano)
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Fiap01.Data;
using Fiap01.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap01.Controllers
{
    public class HomeController : Controller
    {
        private PerguntasContext _context;
        public HomeController(PerguntasContext perguntasContext)
        {
            _context = perguntasContext;
        }
        public IActionResult Index()
        {
            //ViewBag.Nome = "Jean";
            //ViewData["NomeDoAluno"] = $"Outro Nome {DateTime.Now}";
            //var pergunta = new Pergunta()
            //{
            //    Id=1,
            //    Descricao="Que pergunta?",
            //    Autor="Jean"
            //};

            return View(_context.Perguntas.ToList());
        }
        public IActionResult Ajuda()
        {
            return View();
        }
        public IActionResult Sobre()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Pergunta pergunta)
        {
            if (ModelState.IsValid)
            {
                _context.Perguntas.Add(pergunta);
                await _context.SaveChangesAsync();
                var p = pergunta;
            }
            return View();
        } 
    }
}

Controllers/PerguntasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fiap01.Data;
using Fiap01.Models;

namespace Fiap01.Controllers
{
    public class PerguntasController : Controller
    {
        private readonly PerguntasContext _context;

        public PerguntasController(PerguntasContext context)
        {
            _context = context;
        }

        // GET: Perguntas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Perguntas.ToListAsync());
        }

        // GET: Perguntas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pergunta = await _context.Perguntas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pergunta == null)
            {
                return NotFound();
            }

            return View(pergunta);
        }

        // GET: Perguntas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Perguntas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descricao,Autor")] Pergunta pergunta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pergunta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pergunta);
        }

        // GET: Perguntas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pergunta = await _context.Perguntas.FindAsync(id);
            if (pergunta == null)
            {
                return NotFound();
            }
            return View(pergunta);
        }

        // POST: Perguntas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descricao,Autor")] Pergunta pergunta)
        {
            if (id != pergunta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pergunta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerguntaExists(pergunta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pergunta);
        }

        // GET: Perguntas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pergunta = await _context.Perguntas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pergunta == null)
            {
                return NotFound();
            }

            return View(pergunta);
        }

        // POST: Perguntas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pergunta = await _context.Perguntas.FindAsync(id);
            _context.Perguntas.Remove(pergunta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PerguntaExists(int id)
        {
            return _context.Perguntas.Any(e => e.Id == id);
        }
    }
}

Controllers/TopicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Fiap01.Controllers
{
    public class TopicosController : Controller
    {
        public IActionResult Index(string categoria, string topico)
        {
            return View();
        }
    }
}

ViewComponents/NoticiasViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap01.ViewComponents
{
    public class NoticiasViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(int total, bool noticiasUrgentes)
        {
            var view = noticiasUrgentes ? "noticiasUrgentes" : "noticias";
            var itens = GetItens(total);
            return View(view, itens);
        }

        private IEnumerable<Noticia> GetItens(int total)
        {
            for (int i = 0; i < total; i++)
            {
                yield return new Noticia() { Id = i + 1, Titulo=$"Noticia sobre {i}" };
            };
        }
    }

    public class Noticia
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Link { get; set; }
    }
}

Views/Home/Ajuda.cshtml
    <h1>Ajuda</h1>

Views/Home/Create.cshtml
@model Pergunta
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js"></script>

<form action="/home/create" method="post">
    @Html.EditorFor(a => a.Autor)
    @Html.EditorFor(a => a.Descricao)
    @Html.ValidationMessageFor(a => a.Descricao)
    @*<input type="text" name="Descricao" value="" />
        <br />
        <input type="text" name="Autor" value="" />
        <br />*@
    <input type="submit" value="Salvar" />
    <br />
    <br />
    <br />
    <br />
    <br />
    @Html.ValidationSummary()
</form>

Views/Home/Index.cshtml
@model IEnumerable<Pergunta>

<ul>
    @foreach (var item in Model)
    {
        <li>ID: @item.Id</li>
        <li>Descricao: @item.Descricao</li>
        <li>Autor: @item.Autor</li>
    }
</ul>

<h1>Home</h1>
<h1>ViewBag  = @ViewBag.Nome</h1>
<h1>ViewData = @ViewData["NomeDoAluno"]</h1>

<email mail-to="rm330673"></email>

<vc:noticias total="10" noticias-urgentes="false"></vc:noticias>

@*<p>Classe Pergunta</p>
<p>ID: @Model.Id</p>
<p>Descricao: @Model.Descricao</p>
<p>Autor: @Model.Autor</p>*@
<p><img src="~/images.jfif" /></p>

Views/Home/Sobre.cshtml
@{ 
    Layout = "_layoutB";
}
    <h1>Sobre</h1>

Views/Perguntas/Create.cshtml
@model Fiap01.Models.Pergunta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Pergunta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Views/Perguntas/Delete.cshtml
@model Fiap01.Models.Pergunta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pergunta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/Perguntas/Details.cshtml
@model Fiap01.Models.Pergunta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Pergunta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Views/Perguntas/Edit.cshtml
@model Fiap01.Models.Pergunta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Pergunta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Views/Perguntas/Index.cshtml
@model IEnumerable<Fiap01.Models.Pergunta>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

Views/Shared/Components/Noticias/Noticias.cshtml
@model IEnumerable<Fiap01.ViewComponents.Noticia>
@{
}
<ul>
    @foreach (var item in Model)
    {
    <li>
        @item.Id: @item.Titulo
    </li>
    }
</ul>

Views/Shared/Components/Noticias/NoticiasUrgentes.cshtml
@model IEnumerable<Fiap01.ViewComponents.Noticia>
@{
}
<ul>
    @foreach (var item in Model)
    {
        <li style="background-color:red">
            @item.Id: @item.Titulo
        </li>
    }
</ul>

Views/Shared/_layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
</head>
<body>

    <partial name="_menu" />

    @RenderBody()

    <footer>
        Rodapé
    </footer>

</body>
</html>

Views/Shared/_layoutB.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home LayoutB</title>
</head>
<body>

    <partial name="_menu" />

    @RenderBody()

    <footer>
        Rodapé - LayoutB
    </footer>

</body>
</html>

Views/Shared/_menu.cshtml
<nav>
    <ul>
        <li><a href="/home/index">Home</a></li>
        <li><a href="/home/Sobre">Sobre</a></li>
        <li><a href="/home/Ajuda">Ajuda</a></li>
    </ul>
</nav>